import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');

async function generateStatic() {
  try {
    const templatePath = path.resolve(root, 'dist/index.html');
    if (!fs.existsSync(templatePath)) {
      console.warn('dist/index.html not found yet. Run vite build first.');
      return;
    }

    const template = fs.readFileSync(templatePath, 'utf-8');
    
    // Import the ESM server bundle generated by Vite
    const serverBundlePath = path.resolve(root, 'dist/server/main-server.js');
    if (fs.existsSync(serverBundlePath)) {
      const serverModule = await import(serverBundlePath);
      if (typeof serverModule.render === 'function') {
        const { html: appHtml } = serverModule.render();
        const finalHtml = template.replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`);
        fs.writeFileSync(templatePath, finalHtml, 'utf-8');
        console.log('Static HTML pre-rendered successfully into dist/index.html');
      } else {
        console.warn('render function not found in server bundle exports:', Object.keys(serverModule));
      }
    }
  } catch (error) {
    console.error('Error during static generation:', error);
  }
}

generateStatic();
