import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { PRODUCTS, PROMOTIONS, COMBO_OF_THE_MONTH, CATEGORIES } from '../src/constants';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');

async function generateStatic() {
  try {
    const templatePath = path.resolve(root, 'dist/index.html');
    if (!fs.existsSync(templatePath)) {
      console.warn('dist/index.html not found yet. Run client build first.');
      return;
    }

    const template = fs.readFileSync(templatePath, 'utf-8');
    
    // Import the ESM server bundle generated by Vite
    const serverBundlePath = path.resolve(root, 'dist/server/main-server.js');
    if (!fs.existsSync(serverBundlePath)) {
      console.warn('dist/server/main-server.js not found. Skipping static HTML pre-rendering.');
      return;
    }

    const serverModule = await import(serverBundlePath);
    if (typeof serverModule.render !== 'function') {
      console.warn('render function not found in server bundle exports:', Object.keys(serverModule));
      return;
    }

    // Build the list of static routes to pre-render
    const routesToRender: string[] = [
      '/',
      '/quienes-somos',
      '/politica-privacidad',
      '/politica-reembolso',
      '/terminos-servicio',
      '/condiciones-entrega',
      '/devoluciones-garantia',
      '/checkout',
      '/gracias'
    ];

    // Add categories
    for (const cat of CATEGORIES) {
      routesToRender.push(`/categoria/${cat.id}`);
    }
    routesToRender.push('/categoria/combos');

    // Add products
    for (const product of PRODUCTS) {
      routesToRender.push(`/producto/${product.id}`);
    }

    // Add combos
    routesToRender.push(`/combo/${COMBO_OF_THE_MONTH.id}`);
    for (const promo of PROMOTIONS) {
      routesToRender.push(`/combo/${promo.id}`);
    }

    console.log(`Pre-rendering ${routesToRender.length} static routes for Cloudflare...`);

    let renderedCount = 0;
    for (const route of routesToRender) {
      try {
        const { html: appHtml } = serverModule.render(route);
        const finalHtml = template.replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`);

        let targetFile: string;
        if (route === '/') {
          targetFile = templatePath;
        } else {
          const targetDir = path.resolve(root, 'dist', route.replace(/^\//, ''));
          if (!fs.existsSync(targetDir)) {
            fs.mkdirSync(targetDir, { recursive: true });
          }
          targetFile = path.resolve(targetDir, 'index.html');
        }

        fs.writeFileSync(targetFile, finalHtml, 'utf-8');
        renderedCount++;
      } catch (routeErr) {
        console.warn(`Could not pre-render route ${route}:`, routeErr);
      }
    }

    console.log(`Successfully pre-rendered ${renderedCount} static pages into dist/`);

    // Ensure public files exist in dist/
    const publicFiles = ['llms.txt', 'llms-full.txt', 'sitemap.xml', 'robots.txt', '_redirects', '_headers', 'CNAME', '404.html'];
    for (const file of publicFiles) {
      const srcFile = path.resolve(root, 'public', file);
      const dstFile = path.resolve(root, 'dist', file);
      if (fs.existsSync(srcFile)) {
        fs.copyFileSync(srcFile, dstFile);
      }
    }

  } catch (error) {
    console.error('Error during static generation:', error);
  }
}

generateStatic();
